import Head from 'next/head';
import '@styles/globals.css';

function App({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />
    </div>
  );
}
export default App;
